# Generated by Django 4.2.13 on 2024-07-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('idpropriedade', models.AutoField(primary_key=True, serialize=False)),
                ('nomepropriedade', models.CharField(db_column='nomePropriedade', max_length=45)),
            ],
            options={
                'db_table': 'propriedade',
                'managed': False,
            },
        ),
    ]
