# Generated by Django 4.2.13 on 2024-07-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0003_propriedade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idfuncionario', models.AutoField(primary_key=True, serialize=False)),
                ('nomefuncionario', models.CharField(db_column='nomeFuncionario', max_length=45)),
                ('telefonefuncionario', models.CharField(db_column='telefoneFuncionario', max_length=45)),
            ],
            options={
                'db_table': 'funcionariop',
                'managed': False,
            },
        ),
    ]
