# Generated by Django 4.2.13 on 2024-07-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0004_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroGado',
            fields=[
                ('idanimal', models.IntegerField(primary_key=True, serialize=False)),
                ('nomeAnimal', models.CharField(max_length=45)),
                ('dataNascimento', models.DateField()),
                ('raca', models.CharField(max_length=45)),
                ('categoria', models.CharField(max_length=45)),
                ('estadoReprodutivo', models.CharField(max_length=45)),
                ('estadoProdutivo', models.CharField(max_length=45)),
                ('saude', models.CharField(max_length=45)),
                ('gestacao', models.IntegerField(max_length=2)),
                ('partos', models.IntegerField(max_length=2)),
                ('pai', models.CharField(max_length=45)),
                ('mae', models.CharField(max_length=45)),
                ('situacaoNascer', models.CharField(max_length=45)),
                ('tipoParto', models.CharField(max_length=50)),
                ('pesoNascer', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipoAleitamento', models.CharField(max_length=45)),
                ('desmame', models.DateField()),
                ('tipoAcasalamento', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'animal',
                'managed': False,
            },
        ),
    ]
