# Generated by Django 4.2.13 on 2024-07-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0005_cadastrogado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id_producao', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.DateField(db_column='data')),
                ('primeiraordenha', models.DecimalField(db_column='primeiraOrdenha', decimal_places=2, max_digits=10)),
                ('segundaondenha', models.DecimalField(db_column='segundaOrdenha', decimal_places=2, max_digits=10)),
                ('terceiraondenha', models.DecimalField(db_column='terceiraOrdenha', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'producaooredenha',
                'managed': False,
            },
        ),
    ]
