# Generated by Django 4.2.13 on 2024-08-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0006_producao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('idmedicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nomemedicamento', models.CharField(db_column='nomeMedicamento', max_length=45)),
                ('tipomedicamento', models.CharField(db_column='tipoMedicamento', max_length=45)),
                ('Data', models.DateField(db_column='data')),
                ('quantidademedicamento', models.DecimalField(db_column='quantidadeMendicamento', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'medicamento',
                'managed': False,
            },
        ),
    ]
