# Generated by Django 4.2.13 on 2024-08-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0007_medicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('idsaude', models.AutoField(primary_key=True, serialize=False)),
                ('Intercorrencia', models.CharField(db_column='intercorrencia', max_length=45)),
                ('usomedicamento', models.BooleanField(db_column='usoMedicamento', default=False)),
                ('Medicamento', models.CharField(db_column='medicamento', max_length=100)),
                ('Gestacao', models.BooleanField(db_column='gestacao', default=False)),
                ('previsaoparto', models.DateField(db_column='previsaoParto')),
                ('estadoprodutivo', models.CharField(db_column='estadoProdutivo', max_length=45)),
                ('iniciolactacao', models.DateField(db_column='inicioLactacao')),
                ('fimlactacao', models.DateField(db_column='fimLactacao')),
                ('diaslactacao', models.IntegerField(db_column='diasLactacao')),
                ('Morte', models.CharField(db_column='morte', max_length=45)),
            ],
            options={
                'db_table': 'suadeanimal',
                'managed': False,
            },
        ),
    ]
