# Generated by Django 4.2.13 on 2024-08-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0008_animal'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animal',
            table='saudeanimal',
        ),
    ]
