# Generated by Django 4.2.13 on 2024-09-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0009_alter_animal_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuicao',
            fields=[
                ('iddistribuicao', models.AutoField(primary_key=True, serialize=False)),
                ('dataProducao', models.DateField(db_column='dataproducao')),
                ('Consumo', models.DecimalField(db_column='consumo', decimal_places=2, max_digits=5)),
                ('leiteBezerro', models.DecimalField(db_column='leitebezerro', decimal_places=2, max_digits=5)),
                ('Descarte', models.DecimalField(db_column='descarte', decimal_places=2, max_digits=5)),
                ('leiteDistribuido', models.DecimalField(db_column='leitedistribuido', decimal_places=2, max_digits=5)),
                ('localDistribuido', models.CharField(db_column='localdistribuido', max_length=45)),
            ],
            options={
                'db_table': 'distribuicao',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='producao',
            table='producaoordenha',
        ),
    ]
