# Generated by Django 4.2.13 on 2024-09-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0010_distribuicao_alter_producao_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intercorrencia', models.CharField(max_length=45)),
                ('usomedicamento', models.BooleanField(default=False)),
                ('medicamento', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_reprodutivo', models.CharField(max_length=45)),
                ('data_evento', models.DateField(auto_now_add=True)),
                ('peso_atual', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'historico_animal',
                'managed': False,
            },
        ),
    ]
