# Generated by Django 4.2.13 on 2024-10-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0011_historicoanimal'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propriedade',
            table='propriedadet',
        ),
    ]
