# Generated by Django 4.2.13 on 2024-10-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0012_alter_propriedade_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propriedade',
            table='propriedade',
        ),
    ]
