# Generated by Django 4.2.13 on 2024-10-15 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0013_alter_propriedade_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propriedade',
            options={'managed': True},
        ),
    ]
