# Generated by Django 4.2.13 on 2024-10-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0014_alter_propriedade_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propriedade',
            options={'managed': False},
        ),
    ]
