# Generated by Django 4.2.13 on 2024-11-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0015_alter_propriedade_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEvento', models.CharField(db_column='tipo_evento', max_length=100)),
                ('Descricao', models.CharField(db_column='descricao', max_length=255)),
                ('dataEvento', models.DateField(db_column='data_evento')),
            ],
            options={
                'db_table': 'calendariosanitario',
                'managed': False,
            },
        ),
    ]
