# Generated by Django 4.2.13 on 2024-12-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testep', '0016_calendariosanitario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calendariosanitario',
            table='caledariosanitario',
        ),
    ]
